// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektTurnieju.Data;

#nullable disable

namespace ProjektTurnieju.Migrations
{
    [DbContext(typeof(TurniejDBContext))]
    [Migration("20230629131423_revertilisty")]
    partial class revertilisty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjektTurnieju.Models.Druzyna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdKapitanaDruzyny")
                        .HasColumnType("int");

                    b.Property<string>("NazwaDruzyny")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TurniejId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurniejId");

                    b.ToTable("Druzyny");
                });

            modelBuilder.Entity("ProjektTurnieju.Models.Ogloszenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ogloszenia");
                });

            modelBuilder.Entity("ProjektTurnieju.Models.Turniej", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Turniej");
                });

            modelBuilder.Entity("ProjektTurnieju.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyMaDruzyne")
                        .HasColumnType("bit");

                    b.Property<int?>("DruzynaId")
                        .HasColumnType("int");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nick")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rola")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DruzynaId");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("ProjektTurnieju.Models.Druzyna", b =>
                {
                    b.HasOne("ProjektTurnieju.Models.Turniej", null)
                        .WithMany("Druzyny")
                        .HasForeignKey("TurniejId");
                });

            modelBuilder.Entity("ProjektTurnieju.Models.Uzytkownik", b =>
                {
                    b.HasOne("ProjektTurnieju.Models.Druzyna", null)
                        .WithMany("Zawodnicy")
                        .HasForeignKey("DruzynaId");
                });

            modelBuilder.Entity("ProjektTurnieju.Models.Druzyna", b =>
                {
                    b.Navigation("Zawodnicy");
                });

            modelBuilder.Entity("ProjektTurnieju.Models.Turniej", b =>
                {
                    b.Navigation("Druzyny");
                });
#pragma warning restore 612, 618
        }
    }
}
